spring:
  servlet:
    multipart:
      max-file-size: 2048MB # 单个文件最大限制 (设为1GB)
      max-request-size: 2048MB # 单次请求最大总限制
  application:
    name: lzw
  datasource:
    url: jdbc:mysql://localhost:3306/lzw_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080

# MyBatis Plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  map-underscore-to-camel-case: true